export const PATH_ITEM_HEIGHT = 70;
export const PATH_ITEM_HEIGHT_WITH_PADDING = PATH_ITEM_HEIGHT - 10;
export const OVERSCAN_COUNT = 5;
export const SKETELOT_PATH_DESKTOP = 6;
export const SKETELOT_PATH_MOBILE = 3;